name: Multi-arch build & push
on:
  push:
    branches: [ main ]

jobs:
  build-amd64:
    runs-on: ubuntu-24.04
    permissions:
      packages: write
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-buildx-action@v3
      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: docker/build-push-action@v5
        with:
          context: .
          file: ./PreBakeDjango
          platforms: linux/amd64
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/prebakedjango:amd64
          cache-from: type=gha,scope=amd64
          cache-to: type=gha,mode=max,scope=amd64

  build-arm64:
    runs-on: ubuntu-24.04-arm
    permissions:
      packages: write
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-buildx-action@v3
      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: docker/build-push-action@v5
        with:
          context: .
          file: ./PreBakeDjango
          platforms: linux/arm64
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/prebakedjango:arm64
          cache-from: type=gha,scope=arm64
          cache-to: type=gha,mode=max,scope=arm64