name: Multi-arch build & push
on:
  push:
    branches: [ main ]

jobs:
  build:
    strategy:
      matrix:
        include:
          - platform: linux/amd64
            runner: ubuntu-24.04
            cache-scope: amd64
          - platform: linux/arm64
            runner: ubuntu-24.04-arm
            cache-scope: arm64
    runs-on: ${{ matrix.runner }}
    permissions:
      packages: write
    outputs:
      image-digest-amd64: ${{ matrix.platform == 'linux/amd64' && steps.build.outputs.digest || '' }}
      image-digest-arm64: ${{ matrix.platform == 'linux/arm64' && steps.build.outputs.digest || '' }}
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-buildx-action@v3
      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: docker/build-push-action@v5
        id: build
        with:
          context: .
          file: ./PreBakeDjango
          platforms: ${{ matrix.platform }}
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/prebakedjango:${{ matrix.cache-scope }}
          cache-from: type=gha,scope=${{ matrix.cache-scope }}
          cache-to: type=gha,mode=max,scope=${{ matrix.cache-scope }}

  create-manifest:
    needs: build
    runs-on: ubuntu-24.04
    permissions:
      packages: write
    steps:
      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Create and push multi-arch manifest
        run: |
          docker buildx imagetools create \
            --tag ghcr.io/${{ github.repository_owner }}/prebakedjango:latest \
            ghcr.io/${{ github.repository_owner }}/prebakedjango:amd64 \
            ghcr.io/${{ github.repository_owner }}/prebakedjango:arm64